name: Delete CloudFormation Stack for EKS

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./AWS-Eks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Delete CloudFormation stack
        run: |
          aws cloudformation delete-stack \
            --stack-name eks-cluster-stack

      - name: Wait for stack deletion to complete
        run: |
          aws cloudformation wait stack-delete-complete \
            --stack-name eks-cluster-stack
